Profile and settings  modal
swamphacks/HaXr pull request #43
Opened 2024-08-02 05:02 UTC by AlexanderWangY

refer to discord video

profile settings as well as avatars with vercel blob (which you need to set up yourself)

2024-08-25 01:19 UTC, AlexanderWangY commented
@RobertConde Whats the timeline on this PR?

2024-08-25 01:55 UTC, RobertConde commented
24 hrs

2024-08-26 00:26 UTC, RobertConde commented
Don't need migrations, yet. Remove then.

2024-08-26 00:28 UTC, RobertConde commented
Make sure to run `npm run format`

2024-08-26 00:28 UTC, RobertConde requested changes
okie

2024-08-26 00:28 UTC, RobertConde commented on components/settings/tabs/Account.tsx
> +  const form = useForm({
You should do something like `useForm<T>` to specify the type of the form. This also is automatic by specifying initial values I believe (check Configure Competition).

2024-08-26 00:28 UTC, RobertConde commented on components/settings/tabs/Account.tsx
> +  const cleanFormValues = (values: FormValues): Partial<FormValues> => {
You can add `transformValues: (vals) => ...` in the `useForm` hook instead. TS is not happy even though ik what you're doing.

2024-08-26 00:28 UTC, RobertConde commented on components/settings/tabs/Account.tsx
> +      form.setFieldValue('bio', newUserData.bio || '');
Maybe a function should do a bunch of this shared behavior

2024-08-26 00:28 UTC, RobertConde commented on components/settings/tabs/Account.tsx
> +    if (session?.user?.id === undefined) {
nit: `!session?.user?.id`

2024-08-26 00:28 UTC, RobertConde commented on components/settings/tabs/Account.tsx
> +    await deleteUserAvatar(session.user.id);
shouldn't need to be called.

2024-08-26 00:28 UTC, RobertConde commented on actions/user.ts
> +
You should delete previous avatar before before uploading and setting new one here! That way we don't forget to call "`delete`".

2024-08-26 00:28 UTC, RobertConde commented on components/admin/AdminDashboard.tsx
> +  if (status === 'loading') return <Spinner />;
You don't need this... nor dou need the `useSession` hook.

2024-08-26 00:28 UTC, RobertConde commented on components/settings/tabs/Account.tsx
> +    );
Should be `formData.get('file') as File`

2024-08-26 00:28 UTC, RobertConde commented on actions/user.ts
> +  const blob = await put(avatar_image.name, avatar_image, {
Should pass a `File`... not the form

2024-08-26 00:28 UTC, RobertConde commented on actions/user.ts
> +
Define return types to make sure you do what you expect!

2024-08-26 00:28 UTC, RobertConde commented on actions/user.ts
> +      where: {
You don't have to await this. You can just return the Promise itself

2024-08-26 00:28 UTC, RobertConde commented on actions/user.ts
> +      where: {
Same just return the promise

2024-08-26 00:28 UTC, RobertConde commented on actions/user.ts
> +  }
Is probably more descriptive `console.error('Could not delete avatar for user with ID ${user_id}');`

2024-08-26 00:28 UTC, RobertConde commented on components/settings/tabs/Account.tsx
> +        '[ERROR] No session ID. Please contact Technical Staff for help'
People shouldn't be reading this, generally. It could just be "Cannot submit form without a session ID"

2024-08-26 00:28 UTC, RobertConde commented on components/settings/SettingsModal.tsx
> +      fullScreen={isMobile ? true : false}
if true, return true .... hmmm

2024-08-26 00:28 UTC, RobertConde commented on components/settings/SettingsModal.tsx
> +  const [burgerOpen, { toggle, open: openBurger, close: closeBurger }] =
you're not using `openBurger`

2024-08-26 01:07 UTC, AlexanderWangY commented on components/settings/SettingsModal.tsx
> +      fullScreen={isMobile ? true : false}
HAHAHA 😭

2024-08-26 02:01 UTC, AlexanderWangY commented on actions/user.ts
> +  revalidatePath('/');
I just need to re-validate it for everyone (especially if this modal is going to be for both admins and hackers). Therefore I've decided to go with a whole application re-validation.

2024-11-18 06:27 UTC, RobertConde commented
You did it!

2024-11-18 06:27 UTC, closed without merging